export const GET_EMAIL_USER = 'GET_EMAIL_USER';
export const GET_CURRENCIES = 'GET_CURRENCIES';
export const GET_EXPENSES = 'GET_EXPENSES';
export const GET_TOTAL_VALUE_EXPENSES = 'GET_TOTAL_VALUE_EXPENSES';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
